#!/usr/bin/env bash
# aqua-installer - shell script to install aqua

set -eu

version="<< parameters.version >>"
install_path="<< parameters.install_path >>"

if [ -f "$install_path" ]; then
  exit 0
fi

uname_os() {
  local os
  os=$(uname -s | tr '[:upper:]' '[:lower:]')
  case "$os" in
    cygwin_nt*) os="windows" ;;
    mingw*) os="windows" ;;
    msys_nt*) os="windows" ;;
  esac
  echo "$os"
}

uname_arch() {
  local arch
  arch=$(uname -m)
  case $arch in
    x86_64) arch="amd64" ;;
    aarch64) arch="arm64" ;;
  esac
  echo ${arch}
}

OS="$(uname_os)"
ARCH="$(uname_arch)"

mkdir -p "$(dirname "$install_path")"

URL=https://github.com/suzuki-shunsuke/aqua/releases/download/${version}/aqua_${OS}_${ARCH}.tar.gz
tempdir=$(mktemp -d)
echo "===> Downloading $URL ..." >&2
curl --fail -L "$URL" -o "$tempdir/aqua_${OS}_${ARCH}.tar.gz"

(cd "$tempdir"; tar xvzf "aqua_${OS}_${ARCH}.tar.gz" > /dev/null)
echo "===> Install aqua $version ($OS/$ARCH) to $install_path" >&2

mv "$tempdir/aqua" "$install_path"

rm -R "$tempdir"

chmod a+x "$install_path"
